import type { Metadata } from 'next'
import '../globals.css'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { getTranslations } from 'next-intl/server'
import Header from '@/components/header'
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700', '800']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const messages = await getMessages()
  //  const t = await getTranslations('HomePage')

  return (
    <html lang={locale} className={`${poppins.variable}`}>
      <body>
        <div className="page">
          <NextIntlClientProvider messages={messages}>
            <Header/>
            {children}
          </NextIntlClientProvider>
        </div>
      </body>
    </html>
  )
}
